### ISSUE TITLE
Native PHP Enum fails 

### ISSUE THREAD

**Issue by nkamuo** [overblog/GraphQLBundle#1092] opened 2023-01-25 00:52 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             |no
| Version/Branch   |  0.15.2

Using PHP 8.1 native Enum with  #[Enum] Attributes Fails.

I have an Enum File with the following contents

<?php
namespace App\Entity\Transport\Vehicle;
use Overblog\GraphQLBundle\Annotation\Enum;

#[Enum}
enum VehicleStatus: string{
 case PENDING = 'pending';
 case ACTIVE = 'active'; 
}

This leads to the Error:

Invalid type for path "overblog_graphql_types.VehicleStatus._enum_config.values.PENDING.value". Expected "scalar",
  but got "App\Entity\Transport\Vehicle\VehicleStatus".

Any solution for this?

Im running php 8.2

**Comment by Vincz** [comment] 2023-01-25 09:10
Hey @nkamuo! Enum are supposed to work with the latest branch. What is your problem with the Enum? Can you share a piece of code?

**Comment by nkamuo** [comment] 2023-01-25 09:18
I have a PHP Enum File with the Following contents:

<?php
namespace App\Entity\Transport\Vehicle;

use Overblog\GraphQLBundle\Annotation\Enum;
use Overblog\GraphQLBundle\Annotation\EnumValue;


#[Enum()]
enum VehicleStatus: string{

    #[EnumValue()]
    case PENDING = 'pending';

    case ACTIVE = 'active';

    case SUSPENDED = 'suspended';
}
?>

And I get this Error:

 Invalid type for path "overblog_graphql_types.VehicleStatus._enum_config.values.PENDING.value". Expected "scalar",
  but got "App\Entity\Transport\Vehicle\VehicleStatus".

**Comment by Vincz** [comment] 2023-01-25 09:20
Can you post your enum?

**Comment by nkamuo** [comment] 2023-01-25 09:21
`<?php
namespace App\Entity\Transport\Vehicle;
use Overblog\GraphQLBundle\Annotation\Enum;


#[Enum]
enum VehicleStatus: string{

    case PENDING = 'pending';

    case ACTIVE = 'active';

    case SUSPENDED = 'suspended';
}
`

**Comment by fp-cfr** [comment] 2023-01-30 14:33
Same here with `v0.14.`

**Comment by konnisoelch** [comment] 2023-02-08 11:37
Same for me @ `v0.14.`

**Comment by AlexOstrovsky** [comment] 2023-02-09 11:54
Native PHP 8.1 enums work for me on master branch. Are they supposted to work also on 0.15? @Vincz

**Comment by eteos** [comment] 2023-02-21 10:27
I think the issue is that the latest GraphQLBundle version (0.15.2) requires "webonyx/graphql-php": "^14.5", whilst webonyx enum support is in "webonyx/graphql-php": "^15.0"

**Comment by nkamuo** [comment] 2023-05-09 14:01
> Native PHP 8.1 enums work for me on master branch. Are they supposted to work also on 0.15? @Vincz

It doesn't work for me. Do you use any special config to make it work?

**Comment by bogdandubyk** [comment] 2023-05-29 13:54
any updates here? for me still not working, and as far as I can see `v0.15.3` still not released?

**Comment by Vincz** [comment] 2023-05-29 14:01
Hi @bogdandubyk! We are waiting a couple of days for #1119, #1071 and #1108 to get fixed by their respective contributors and we will publish a new release.

**Comment by bogdandubyk** [comment] 2023-05-29 15:14
sure, thank you for the quick response, I'll use dev-master for now on the local machine

**Comment by vladdnepr** [comment] 2023-07-07 07:49
> Hi @bogdandubyk! We are waiting a couple of days for #1119, #1071 and #1108 to get fixed by their respective contributors and we will publish a new release.

Sorry, but now I don't have free time for #1108 

Maybe we release this issue later in another release?

**Closed** 2023-07-07 08:30 UTC
