### ISSUE TITLE
Generated Classes Throwing Warning for Deprecated Use of call_user_func_array

### ISSUE THREAD

**Issue by efredine** [overblog/GraphQLBundle#649] opened 2020-02-05 16:11 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes 
| Feature request? |  no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.12.6

The generated classes are using `call_user_func_array` in a way that has been deprecated. Example warning:
`PHP Deprecated:  call_user_func_array() expects parameter 1 to be a valid callback, non-static method Bean\APIBundle\GraphQL\Type\Scalar\DateTimeScalar::serialize() should not be called statically in /var/www/html/src/generated/graphql/Types/DateTimeType.php on line 24`

It's caused by this line in the generated class:
` return \call_user_func_array(['Bean\\APIBundle\\GraphQL\\Type\\Scalar\\DateTimeScalar', 'serialize'], \func_get_args());
`

**Comment by mcg-web** [comment] 2020-02-18 06:57
This is [the normal behavior](https://github.com/overblog/GraphQLBundle/blob/master/docs/definitions/type-system/scalars.md#with-yaml) custom scalar should be define using 3 static functions. You can use [the PHP way](https://github.com/overblog/GraphQLBundle/blob/master/docs/definitions/type-system/index.md#type-system)  if needed to define your custom scalar type. I'm closing this since this not a bug, feel free anyway to continue discussion here.

**Closed by mcg-web** 2020-02-18 06:57 UTC
Labels: question
