### ISSUE TITLE
Interfaces / inheritance not working (Runtime Object type A is not a possible type for B.)

### ISSUE THREAD

**Issue by paoloposo** [overblog/GraphQLBundle#344] opened 2018-06-11 22:13 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.11.0

In my php model, i have an abstract class `Acme\\Entity\\User` with some fields, say `displayName` and `username`. I also have a concrete class `Acme\\Entity\\LocalUser` which extends `User` and has additional fields, say `firstName` and `lastName`.

I want to represent that same model in GraphQL. Following the [type inheritance documentation](https://github.com/overblog/GraphQLBundle/blob/0.11/Resources/doc/definitions/type-inheritance.md), I ended up with this schema:

    Query:    # root query
      type: object
      config:
        fields:
          user:
            type: User
            args:
              username: String
              self: Boolean
            resolve: '@=resolver(''my_user_resolver'', [args])'

    User:
      type: interface
      config:
        fields:
          username:
            type: "String"
          displayName:
            type: "String" 
        resolveType: '@=resolver(''my_usertype_resolver'', [value])' # returns string 'LocalUser'
		
    LocalUser:
      type: object
      inherits:
        - User
      config:
        fields:
          firstName:
            type: "String"
          lastName:
            type: "String"

However, when I send a query that has to do with these types, like:

	{
	  user(self: true) {
	   displayName
	  }
	}

I get the following error:

> {
  "errors": [
&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;  "debugMessage": "Runtime Object type \\"LocalUser\\" is not a possible type for \\"User\\".",
&nbsp;&nbsp;&nbsp;&nbsp;  "message": "Internal server Error",
&nbsp;&nbsp;&nbsp;&nbsp;  "category": "internal",
&nbsp;&nbsp;&nbsp;&nbsp;  "locations": [
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  "line": 2,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  "column": 3
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;  ],
&nbsp;&nbsp;&nbsp;&nbsp;  "path": [
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"user"
&nbsp;&nbsp;&nbsp;&nbsp;  ],
&nbsp;&nbsp;&nbsp;&nbsp;  "trace": [
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  "file": "\\\\My\\\\Project\\\\Location\\\\vendor\\\\webonyx\\\\graphql-php\\\\src\\\\Executor\\\\Executor.php",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  "line": 1106,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  "call": "GraphQL\\\\Executor\\\\Executor::ensureValidRuntimeType('LocalUser', GraphQLType: User, instance of ArrayObject(1), instance of GraphQL\\\\Type\\\\Definition\\\\ResolveInfo, instance of Acme\\\\Entity\\\\LocalUser)"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;...
&nbsp;&nbsp;&nbsp;&nbsp;  ],
&nbsp;&nbsp;&nbsp;&nbsp;  "data": {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"user": null
&nbsp;&nbsp;&nbsp;&nbsp;  }
&nbsp;&nbsp;&nbsp;&nbsp;}
}

Also when I use an inline-fragment, I get a slightly differently formulated error, though it essentially says the same:

    {
      user(self: true) {
        displayName
        ... on LocalUser {
          firstName
        }
      }
    }

> {
&nbsp;&nbsp;"errors":&nbsp;[
&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"message":&nbsp;"Fragment&nbsp;cannot&nbsp;be&nbsp;spread&nbsp;here&nbsp;as&nbsp;objects&nbsp;of&nbsp;type&nbsp;\"User\"&nbsp;can&nbsp;never&nbsp;be&nbsp;of&nbsp;type&nbsp;\"LocalUser\".",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"category":&nbsp;"graphql",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"locations":&nbsp;[
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"line":&nbsp;4,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"column":&nbsp;5
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;]
}

### Things I tried which didn't work
- **declaring `User` as object**
With this I can get fields of `User`, but still can't use inline-fragments to get fields of `LocalUser` (Fragment cannot be spread here as objects of type \"User\" can never be of type \"LocalUser\".")

- **added `heirs: [ LocalUser ]` to `User`**
I tried this with `User` as interface as well as object, neither did work.

- **explicitly declare `LocalUser`**
As described in the [upgrade guide](https://github.com/overblog/GraphQLBundle/blob/master/UPGRADE-0.11.md#explicitly-declare-non-detected-types). Had no effect.

- **clearing cache after all the above**
No effect.

**Comment by mcg-web** [comment] 2018-06-12 05:35
Your User type only inherits of LocalUser config (fields) this does not replace graphQL interface implementation. You still have to explicit declare that user implement  LocalUser:

```diff
LocalUser:
  type: object
  inherits:
    - User
  config:
+   interfaces: [LocalUser]
    fields:
      firstName:
        type: "String"
      lastName:
        type: "String"
```

I'm closing this since it is not a bug but feel free to continue discussion if needed :+1:

**Closed by mcg-web** 2018-06-12 05:35 UTC

**Comment by bastos71** [comment] 2018-12-03 15:16
@mcg-web could you please update `GraphQLBundle/docs/definitions/type-system/interface.md` to introduce a basic usage example of an interface please ?

**Comment by mcg-web** [comment] 2018-12-03 15:23
@bastos71 we have in plan to rewrite totally the documentation introducing some examples but we missing time right now, you can find a complete example here https://github.com/mcg-web/graphql-symfony-doctrine-sandbox/tree/master/src/AppBundle/Resources/config/graphql

**Comment by murilozilli** [comment] 2021-06-23 00:47
Using relay and having the parent interfacing Node this doesnt work

```
Post:
  type: interface
  config:
    description: A post created by recruiter or agency admin
    interfaces: [Node]
    fields:
      id:
        builder: "Relay::GlobalId"

JobPost:
  type: object
  inherits: [Post]
  config:
    interfaces: [Post]
    fields:
      subtitle:
        type: String
```

I get `Unrecognized option "interfaces" under "overblog_graphql_types.Post._interface_config". Available options are "description", "fields", "name", "resolveType".`

if I try to change and use only inherit on post for node

```
Post:
  type: interface
  inherits: [Node]
  config:
    description: A post created by recruiter or agency admin
    fields:
      id:
        builder: "Relay::GlobalId"
```

than i get:
`Fragment cannot be spread here as objects of type "Node" can never be of type "Post".`
`Fragment cannot be spread here as objects of type "Node" can never be of type "JobPost".`

And with my initial configuration which was Post as object interfacing Node and JobPost inherting Post than I get OP's problem
